module q3a50Static
#
# NB: this file was automatically generated by Dynare
#     from q3a50.mod
#
using Utils

export static!

function static!(y::Vector{Float64}, x::Vector{Float64}, params::Vector{Float64},
                 residual::Vector{Float64})
#=
## Function Arguments

## Input
 1 y:         Array{Float64, length(model.endo), 1}             Vector of endogenous variables in declaration order
 2 x:         Array{Float64, length(model.exo), 1}              Vector of exogenous variables in declaration order
 3 params:    Array{Float64, length(model.param), 1}            Vector of parameter values in declaration order

## Output
 4 residual:  Array(Float64, model.eq_nbr, 1)                   Vector of residuals of the static model equations
                                                                in order of declaration of the equations.
                                                                Dynare may prepend auxiliary equations, see model.aux_vars
=#
  @assert length(y) == 101
  @assert length(x) == 51
  @assert length(params) == 9
  @assert length(residual) == 101
  #
  # Model equations
  #
  @inbounds const T11 = y[1]^(-params[2])
  @inbounds const T19 = T11*params[1]
  @inbounds const T23 = 1-params[4]
  @inbounds const T27 = params[5]-1
  @inbounds const T28 = y[3]^T27
  @inbounds const T30 = T23+params[5]*y[2]*T28
  @inbounds const T49 = y[5]^T27
  @inbounds const T51 = T23+params[5]*y[4]*T49
  @inbounds const T67 = y[7]^T27
  @inbounds const T69 = T23+params[5]*y[6]*T67
  @inbounds const T85 = y[9]^T27
  @inbounds const T87 = T23+params[5]*y[8]*T85
  @inbounds const T103 = y[11]^T27
  @inbounds const T105 = T23+params[5]*y[10]*T103
  @inbounds const T121 = y[13]^T27
  @inbounds const T123 = T23+params[5]*y[12]*T121
  @inbounds const T139 = y[15]^T27
  @inbounds const T141 = T23+params[5]*y[14]*T139
  @inbounds const T157 = y[17]^T27
  @inbounds const T159 = T23+params[5]*y[16]*T157
  @inbounds const T175 = y[19]^T27
  @inbounds const T177 = T23+params[5]*y[18]*T175
  @inbounds const T193 = y[21]^T27
  @inbounds const T195 = T23+params[5]*y[20]*T193
  @inbounds const T211 = y[23]^T27
  @inbounds const T213 = T23+params[5]*y[22]*T211
  @inbounds const T229 = y[25]^T27
  @inbounds const T231 = T23+params[5]*y[24]*T229
  @inbounds const T247 = y[27]^T27
  @inbounds const T249 = T23+params[5]*y[26]*T247
  @inbounds const T265 = y[29]^T27
  @inbounds const T267 = T23+params[5]*y[28]*T265
  @inbounds const T283 = y[31]^T27
  @inbounds const T285 = T23+params[5]*y[30]*T283
  @inbounds const T301 = y[33]^T27
  @inbounds const T303 = T23+params[5]*y[32]*T301
  @inbounds const T319 = y[35]^T27
  @inbounds const T321 = T23+params[5]*y[34]*T319
  @inbounds const T337 = y[37]^T27
  @inbounds const T339 = T23+params[5]*y[36]*T337
  @inbounds const T355 = y[39]^T27
  @inbounds const T357 = T23+params[5]*y[38]*T355
  @inbounds const T373 = y[41]^T27
  @inbounds const T375 = T23+params[5]*y[40]*T373
  @inbounds const T391 = y[43]^T27
  @inbounds const T393 = T23+params[5]*y[42]*T391
  @inbounds const T409 = y[45]^T27
  @inbounds const T411 = T23+params[5]*y[44]*T409
  @inbounds const T427 = y[47]^T27
  @inbounds const T429 = T23+params[5]*y[46]*T427
  @inbounds const T445 = y[49]^T27
  @inbounds const T447 = T23+params[5]*y[48]*T445
  @inbounds const T463 = y[51]^T27
  @inbounds const T465 = T23+params[5]*y[50]*T463
  @inbounds const T481 = y[53]^T27
  @inbounds const T483 = T23+params[5]*y[52]*T481
  @inbounds const T499 = y[55]^T27
  @inbounds const T501 = T23+params[5]*y[54]*T499
  @inbounds const T517 = y[57]^T27
  @inbounds const T519 = T23+params[5]*y[56]*T517
  @inbounds const T535 = y[59]^T27
  @inbounds const T537 = T23+params[5]*y[58]*T535
  @inbounds const T553 = y[61]^T27
  @inbounds const T555 = T23+params[5]*y[60]*T553
  @inbounds const T571 = y[63]^T27
  @inbounds const T573 = T23+params[5]*y[62]*T571
  @inbounds const T589 = y[65]^T27
  @inbounds const T591 = T23+params[5]*y[64]*T589
  @inbounds const T607 = y[67]^T27
  @inbounds const T609 = T23+params[5]*y[66]*T607
  @inbounds const T625 = y[69]^T27
  @inbounds const T627 = T23+params[5]*y[68]*T625
  @inbounds const T643 = y[71]^T27
  @inbounds const T645 = T23+params[5]*y[70]*T643
  @inbounds const T661 = y[73]^T27
  @inbounds const T663 = T23+params[5]*y[72]*T661
  @inbounds const T679 = y[75]^T27
  @inbounds const T681 = T23+params[5]*y[74]*T679
  @inbounds const T697 = y[77]^T27
  @inbounds const T699 = T23+params[5]*y[76]*T697
  @inbounds const T715 = y[79]^T27
  @inbounds const T717 = T23+params[5]*y[78]*T715
  @inbounds const T733 = y[81]^T27
  @inbounds const T735 = T23+params[5]*y[80]*T733
  @inbounds const T751 = y[83]^T27
  @inbounds const T753 = T23+params[5]*y[82]*T751
  @inbounds const T769 = y[85]^T27
  @inbounds const T771 = T23+params[5]*y[84]*T769
  @inbounds const T787 = y[87]^T27
  @inbounds const T789 = T23+params[5]*y[86]*T787
  @inbounds const T805 = y[89]^T27
  @inbounds const T807 = T23+params[5]*y[88]*T805
  @inbounds const T823 = y[91]^T27
  @inbounds const T825 = T23+params[5]*y[90]*T823
  @inbounds const T841 = y[93]^T27
  @inbounds const T843 = T23+params[5]*y[92]*T841
  @inbounds const T859 = y[95]^T27
  @inbounds const T861 = T23+params[5]*y[94]*T859
  @inbounds const T877 = y[97]^T27
  @inbounds const T879 = T23+params[5]*y[96]*T877
  @inbounds const T895 = y[99]^T27
  @inbounds const T897 = T23+params[5]*y[98]*T895
  @inbounds const T913 = y[101]^T27
  @inbounds const T915 = T23+params[5]*y[100]*T913
  @inbounds const T1077 = y[3]^params[5]
  @inbounds const T1079 = y[5]^params[5]
  @inbounds const T1082 = y[7]^params[5]
  @inbounds const T1085 = y[9]^params[5]
  @inbounds const T1088 = y[11]^params[5]
  @inbounds const T1091 = y[13]^params[5]
  @inbounds const T1094 = y[15]^params[5]
  @inbounds const T1097 = y[17]^params[5]
  @inbounds const T1100 = y[19]^params[5]
  @inbounds const T1103 = y[21]^params[5]
  @inbounds const T1106 = y[23]^params[5]
  @inbounds const T1109 = y[25]^params[5]
  @inbounds const T1112 = y[27]^params[5]
  @inbounds const T1115 = y[29]^params[5]
  @inbounds const T1118 = y[31]^params[5]
  @inbounds const T1121 = y[33]^params[5]
  @inbounds const T1124 = y[35]^params[5]
  @inbounds const T1127 = y[37]^params[5]
  @inbounds const T1130 = y[39]^params[5]
  @inbounds const T1133 = y[41]^params[5]
  @inbounds const T1136 = y[43]^params[5]
  @inbounds const T1139 = y[45]^params[5]
  @inbounds const T1142 = y[47]^params[5]
  @inbounds const T1145 = y[49]^params[5]
  @inbounds const T1148 = y[51]^params[5]
  @inbounds const T1151 = y[53]^params[5]
  @inbounds const T1154 = y[55]^params[5]
  @inbounds const T1157 = y[57]^params[5]
  @inbounds const T1160 = y[59]^params[5]
  @inbounds const T1163 = y[61]^params[5]
  @inbounds const T1166 = y[63]^params[5]
  @inbounds const T1169 = y[65]^params[5]
  @inbounds const T1172 = y[67]^params[5]
  @inbounds const T1175 = y[69]^params[5]
  @inbounds const T1178 = y[71]^params[5]
  @inbounds const T1181 = y[73]^params[5]
  @inbounds const T1184 = y[75]^params[5]
  @inbounds const T1187 = y[77]^params[5]
  @inbounds const T1190 = y[79]^params[5]
  @inbounds const T1193 = y[81]^params[5]
  @inbounds const T1196 = y[83]^params[5]
  @inbounds const T1199 = y[85]^params[5]
  @inbounds const T1202 = y[87]^params[5]
  @inbounds const T1205 = y[89]^params[5]
  @inbounds const T1208 = y[91]^params[5]
  @inbounds const T1211 = y[93]^params[5]
  @inbounds const T1214 = y[95]^params[5]
  @inbounds const T1217 = y[97]^params[5]
  @inbounds const T1220 = y[99]^params[5]
  @inbounds const T1223 = y[101]^params[5]
  @inbounds lhs =T11;
  @inbounds rhs =T19*T30;
  @inbounds residual[1]= lhs-rhs;
  @inbounds lhs =log(y[2]);
  @inbounds rhs =log(y[2])*params[6]+params[8]*(x[1]+x[2]);
  @inbounds residual[2]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T51;
  @inbounds residual[3]= lhs-rhs;
  @inbounds lhs =log(y[4]);
  @inbounds rhs =params[6]*log(y[4])+params[8]*(x[1]+x[3]);
  @inbounds residual[4]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T69;
  @inbounds residual[5]= lhs-rhs;
  @inbounds lhs =log(y[6]);
  @inbounds rhs =params[6]*log(y[6])+params[8]*(x[1]+x[4]);
  @inbounds residual[6]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T87;
  @inbounds residual[7]= lhs-rhs;
  @inbounds lhs =log(y[8]);
  @inbounds rhs =params[6]*log(y[8])+params[8]*(x[1]+x[5]);
  @inbounds residual[8]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T105;
  @inbounds residual[9]= lhs-rhs;
  @inbounds lhs =log(y[10]);
  @inbounds rhs =params[6]*log(y[10])+params[8]*(x[1]+x[6]);
  @inbounds residual[10]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T123;
  @inbounds residual[11]= lhs-rhs;
  @inbounds lhs =log(y[12]);
  @inbounds rhs =params[6]*log(y[12])+params[8]*(x[1]+x[7]);
  @inbounds residual[12]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T141;
  @inbounds residual[13]= lhs-rhs;
  @inbounds lhs =log(y[14]);
  @inbounds rhs =params[6]*log(y[14])+params[8]*(x[1]+x[8]);
  @inbounds residual[14]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T159;
  @inbounds residual[15]= lhs-rhs;
  @inbounds lhs =log(y[16]);
  @inbounds rhs =params[6]*log(y[16])+params[8]*(x[1]+x[9]);
  @inbounds residual[16]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T177;
  @inbounds residual[17]= lhs-rhs;
  @inbounds lhs =log(y[18]);
  @inbounds rhs =params[6]*log(y[18])+params[8]*(x[1]+x[10]);
  @inbounds residual[18]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T195;
  @inbounds residual[19]= lhs-rhs;
  @inbounds lhs =log(y[20]);
  @inbounds rhs =params[6]*log(y[20])+params[8]*(x[1]+x[11]);
  @inbounds residual[20]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T213;
  @inbounds residual[21]= lhs-rhs;
  @inbounds lhs =log(y[22]);
  @inbounds rhs =params[6]*log(y[22])+params[8]*(x[1]+x[12]);
  @inbounds residual[22]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T231;
  @inbounds residual[23]= lhs-rhs;
  @inbounds lhs =log(y[24]);
  @inbounds rhs =params[6]*log(y[24])+params[8]*(x[1]+x[13]);
  @inbounds residual[24]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T249;
  @inbounds residual[25]= lhs-rhs;
  @inbounds lhs =log(y[26]);
  @inbounds rhs =params[6]*log(y[26])+params[8]*(x[1]+x[14]);
  @inbounds residual[26]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T267;
  @inbounds residual[27]= lhs-rhs;
  @inbounds lhs =log(y[28]);
  @inbounds rhs =params[6]*log(y[28])+params[8]*(x[1]+x[15]);
  @inbounds residual[28]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T285;
  @inbounds residual[29]= lhs-rhs;
  @inbounds lhs =log(y[30]);
  @inbounds rhs =params[6]*log(y[30])+params[8]*(x[1]+x[16]);
  @inbounds residual[30]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T303;
  @inbounds residual[31]= lhs-rhs;
  @inbounds lhs =log(y[32]);
  @inbounds rhs =params[6]*log(y[32])+params[8]*(x[1]+x[17]);
  @inbounds residual[32]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T321;
  @inbounds residual[33]= lhs-rhs;
  @inbounds lhs =log(y[34]);
  @inbounds rhs =params[6]*log(y[34])+params[8]*(x[1]+x[18]);
  @inbounds residual[34]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T339;
  @inbounds residual[35]= lhs-rhs;
  @inbounds lhs =log(y[36]);
  @inbounds rhs =params[6]*log(y[36])+params[8]*(x[1]+x[19]);
  @inbounds residual[36]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T357;
  @inbounds residual[37]= lhs-rhs;
  @inbounds lhs =log(y[38]);
  @inbounds rhs =params[6]*log(y[38])+params[8]*(x[1]+x[20]);
  @inbounds residual[38]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T375;
  @inbounds residual[39]= lhs-rhs;
  @inbounds lhs =log(y[40]);
  @inbounds rhs =params[6]*log(y[40])+params[8]*(x[1]+x[21]);
  @inbounds residual[40]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T393;
  @inbounds residual[41]= lhs-rhs;
  @inbounds lhs =log(y[42]);
  @inbounds rhs =params[6]*log(y[42])+params[8]*(x[1]+x[22]);
  @inbounds residual[42]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T411;
  @inbounds residual[43]= lhs-rhs;
  @inbounds lhs =log(y[44]);
  @inbounds rhs =params[6]*log(y[44])+params[8]*(x[1]+x[23]);
  @inbounds residual[44]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T429;
  @inbounds residual[45]= lhs-rhs;
  @inbounds lhs =log(y[46]);
  @inbounds rhs =params[6]*log(y[46])+params[8]*(x[1]+x[24]);
  @inbounds residual[46]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T447;
  @inbounds residual[47]= lhs-rhs;
  @inbounds lhs =log(y[48]);
  @inbounds rhs =params[6]*log(y[48])+params[8]*(x[1]+x[25]);
  @inbounds residual[48]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T465;
  @inbounds residual[49]= lhs-rhs;
  @inbounds lhs =log(y[50]);
  @inbounds rhs =params[6]*log(y[50])+params[8]*(x[1]+x[26]);
  @inbounds residual[50]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T483;
  @inbounds residual[51]= lhs-rhs;
  @inbounds lhs =log(y[52]);
  @inbounds rhs =params[6]*log(y[52])+params[8]*(x[1]+x[27]);
  @inbounds residual[52]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T501;
  @inbounds residual[53]= lhs-rhs;
  @inbounds lhs =log(y[54]);
  @inbounds rhs =params[6]*log(y[54])+params[8]*(x[1]+x[28]);
  @inbounds residual[54]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T519;
  @inbounds residual[55]= lhs-rhs;
  @inbounds lhs =log(y[56]);
  @inbounds rhs =params[6]*log(y[56])+params[8]*(x[1]+x[29]);
  @inbounds residual[56]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T537;
  @inbounds residual[57]= lhs-rhs;
  @inbounds lhs =log(y[58]);
  @inbounds rhs =params[6]*log(y[58])+params[8]*(x[1]+x[30]);
  @inbounds residual[58]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T555;
  @inbounds residual[59]= lhs-rhs;
  @inbounds lhs =log(y[60]);
  @inbounds rhs =params[6]*log(y[60])+params[8]*(x[1]+x[31]);
  @inbounds residual[60]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T573;
  @inbounds residual[61]= lhs-rhs;
  @inbounds lhs =log(y[62]);
  @inbounds rhs =params[6]*log(y[62])+params[8]*(x[1]+x[32]);
  @inbounds residual[62]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T591;
  @inbounds residual[63]= lhs-rhs;
  @inbounds lhs =log(y[64]);
  @inbounds rhs =params[6]*log(y[64])+params[8]*(x[1]+x[33]);
  @inbounds residual[64]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T609;
  @inbounds residual[65]= lhs-rhs;
  @inbounds lhs =log(y[66]);
  @inbounds rhs =params[6]*log(y[66])+params[8]*(x[1]+x[34]);
  @inbounds residual[66]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T627;
  @inbounds residual[67]= lhs-rhs;
  @inbounds lhs =log(y[68]);
  @inbounds rhs =params[6]*log(y[68])+params[8]*(x[1]+x[35]);
  @inbounds residual[68]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T645;
  @inbounds residual[69]= lhs-rhs;
  @inbounds lhs =log(y[70]);
  @inbounds rhs =params[6]*log(y[70])+params[8]*(x[1]+x[36]);
  @inbounds residual[70]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T663;
  @inbounds residual[71]= lhs-rhs;
  @inbounds lhs =log(y[72]);
  @inbounds rhs =params[6]*log(y[72])+params[8]*(x[1]+x[37]);
  @inbounds residual[72]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T681;
  @inbounds residual[73]= lhs-rhs;
  @inbounds lhs =log(y[74]);
  @inbounds rhs =params[6]*log(y[74])+params[8]*(x[1]+x[38]);
  @inbounds residual[74]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T699;
  @inbounds residual[75]= lhs-rhs;
  @inbounds lhs =log(y[76]);
  @inbounds rhs =params[6]*log(y[76])+params[8]*(x[1]+x[39]);
  @inbounds residual[76]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T717;
  @inbounds residual[77]= lhs-rhs;
  @inbounds lhs =log(y[78]);
  @inbounds rhs =params[6]*log(y[78])+params[8]*(x[1]+x[40]);
  @inbounds residual[78]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T735;
  @inbounds residual[79]= lhs-rhs;
  @inbounds lhs =log(y[80]);
  @inbounds rhs =params[6]*log(y[80])+params[8]*(x[1]+x[41]);
  @inbounds residual[80]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T753;
  @inbounds residual[81]= lhs-rhs;
  @inbounds lhs =log(y[82]);
  @inbounds rhs =params[6]*log(y[82])+params[8]*(x[1]+x[42]);
  @inbounds residual[82]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T771;
  @inbounds residual[83]= lhs-rhs;
  @inbounds lhs =log(y[84]);
  @inbounds rhs =params[6]*log(y[84])+params[8]*(x[1]+x[43]);
  @inbounds residual[84]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T789;
  @inbounds residual[85]= lhs-rhs;
  @inbounds lhs =log(y[86]);
  @inbounds rhs =params[6]*log(y[86])+params[8]*(x[1]+x[44]);
  @inbounds residual[86]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T807;
  @inbounds residual[87]= lhs-rhs;
  @inbounds lhs =log(y[88]);
  @inbounds rhs =params[6]*log(y[88])+params[8]*(x[1]+x[45]);
  @inbounds residual[88]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T825;
  @inbounds residual[89]= lhs-rhs;
  @inbounds lhs =log(y[90]);
  @inbounds rhs =params[6]*log(y[90])+params[8]*(x[1]+x[46]);
  @inbounds residual[90]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T843;
  @inbounds residual[91]= lhs-rhs;
  @inbounds lhs =log(y[92]);
  @inbounds rhs =params[6]*log(y[92])+params[8]*(x[1]+x[47]);
  @inbounds residual[92]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T861;
  @inbounds residual[93]= lhs-rhs;
  @inbounds lhs =log(y[94]);
  @inbounds rhs =params[6]*log(y[94])+params[8]*(x[1]+x[48]);
  @inbounds residual[94]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T879;
  @inbounds residual[95]= lhs-rhs;
  @inbounds lhs =log(y[96]);
  @inbounds rhs =params[6]*log(y[96])+params[8]*(x[1]+x[49]);
  @inbounds residual[96]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T897;
  @inbounds residual[97]= lhs-rhs;
  @inbounds lhs =log(y[98]);
  @inbounds rhs =params[6]*log(y[98])+params[8]*(x[1]+x[50]);
  @inbounds residual[98]= lhs-rhs;
  @inbounds lhs =T11;
  @inbounds rhs =T19*T915;
  @inbounds residual[99]= lhs-rhs;
  @inbounds lhs =log(y[100]);
  @inbounds rhs =params[6]*log(y[100])+params[8]*(x[1]+x[51]);
  @inbounds residual[100]= lhs-rhs;
  @inbounds lhs =y[101]+y[99]+y[97]+y[95]+y[93]+y[91]+y[89]+y[87]+y[85]+y[83]+y[81]+y[79]+y[77]+y[75]+y[73]+y[71]+y[69]+y[67]+y[65]+y[63]+y[61]+y[59]+y[57]+y[55]+y[53]+y[51]+y[49]+y[47]+y[45]+y[43]+y[41]+y[39]+y[37]+y[35]+y[33]+y[31]+y[29]+y[27]+y[25]+y[23]+y[21]+y[19]+y[17]+y[15]+y[13]+y[11]+y[9]+y[7]+y[5]+y[3]+y[1]*params[9]-y[3]*T23-T23*y[5]-T23*y[7]-T23*y[9]-T23*y[11]-T23*y[13]-T23*y[15]-T23*y[17]-T23*y[19]-T23*y[21]-T23*y[23]-T23*y[25]-T23*y[27]-T23*y[29]-T23*y[31]-T23*y[33]-T23*y[35]-T23*y[37]-T23*y[39]-T23*y[41]-T23*y[43]-T23*y[45]-T23*y[47]-T23*y[49]-T23*y[51]-T23*y[53]-T23*y[55]-T23*y[57]-T23*y[59]-T23*y[61]-T23*y[63]-T23*y[65]-T23*y[67]-T23*y[69]-T23*y[71]-T23*y[73]-T23*y[75]-T23*y[77]-T23*y[79]-T23*y[81]-T23*y[83]-T23*y[85]-T23*y[87]-T23*y[89]-T23*y[91]-T23*y[93]-T23*y[95]-T23*y[97]-T23*y[99]-T23*y[101];
  @inbounds rhs =y[2]*T1077+y[4]*T1079+y[6]*T1082+y[8]*T1085+y[10]*T1088+y[12]*T1091+y[14]*T1094+y[16]*T1097+y[18]*T1100+y[20]*T1103+y[22]*T1106+y[24]*T1109+y[26]*T1112+y[28]*T1115+y[30]*T1118+y[32]*T1121+y[34]*T1124+y[36]*T1127+y[38]*T1130+y[40]*T1133+y[42]*T1136+y[44]*T1139+y[46]*T1142+y[48]*T1145+y[50]*T1148+y[52]*T1151+y[54]*T1154+y[56]*T1157+y[58]*T1160+y[60]*T1163+y[62]*T1166+y[64]*T1169+y[66]*T1172+y[68]*T1175+y[70]*T1178+y[72]*T1181+y[74]*T1184+y[76]*T1187+y[78]*T1190+y[80]*T1193+y[82]*T1196+y[84]*T1199+y[86]*T1202+y[88]*T1205+y[90]*T1208+y[92]*T1211+y[94]*T1214+y[96]*T1217+y[98]*T1220+y[100]*T1223;
  @inbounds residual[101]= lhs-rhs;
if ~isreal(residual)
  residual = real(residual)+imag(residual).^2;
end
end

function static!(y::Vector{Float64}, x::Vector{Float64}, params::Vector{Float64},
                 residual::Vector{Float64}, g1::Matrix{Float64})
#=
## Function Arguments

## Input
 1 y:         Array{Float64, length(model.endo), 1}             Vector of endogenous variables in declaration order
 2 x:         Array{Float64, length(model.exo), 1}              Vector of exogenous variables in declaration order
 3 params:    Array{Float64, length(model.param), 1}            Vector of parameter values in declaration order

## Output
 4 residual:  Array(Float64, model.eq_nbr, 1)                   Vector of residuals of the static model equations
                                                                in order of declaration of the equations.
                                                                Dynare may prepend auxiliary equations, see model.aux_vars
 5 g1:        Array(Float64, model.eq_nbr, length(model.endo))  Jacobian matrix of the static model equations;
                                                                columns: variables in declaration order
                                                                rows: equations in order of declaration
=#
  @assert size(g1) == (101, 101)
  fill!(g1, 0.0)
  static!(y, x, params, residual)
  #
  # Jacobian matrix
  #
  @inbounds const T11 = y[1]^(-params[2])
  @inbounds const T19 = T11*params[1]
  @inbounds const T23 = 1-params[4]
  @inbounds const T27 = params[5]-1
  @inbounds const T28 = y[3]^T27
  @inbounds const T30 = T23+params[5]*y[2]*T28
  @inbounds const T49 = y[5]^T27
  @inbounds const T51 = T23+params[5]*y[4]*T49
  @inbounds const T67 = y[7]^T27
  @inbounds const T69 = T23+params[5]*y[6]*T67
  @inbounds const T85 = y[9]^T27
  @inbounds const T87 = T23+params[5]*y[8]*T85
  @inbounds const T103 = y[11]^T27
  @inbounds const T105 = T23+params[5]*y[10]*T103
  @inbounds const T121 = y[13]^T27
  @inbounds const T123 = T23+params[5]*y[12]*T121
  @inbounds const T139 = y[15]^T27
  @inbounds const T141 = T23+params[5]*y[14]*T139
  @inbounds const T157 = y[17]^T27
  @inbounds const T159 = T23+params[5]*y[16]*T157
  @inbounds const T175 = y[19]^T27
  @inbounds const T177 = T23+params[5]*y[18]*T175
  @inbounds const T193 = y[21]^T27
  @inbounds const T195 = T23+params[5]*y[20]*T193
  @inbounds const T211 = y[23]^T27
  @inbounds const T213 = T23+params[5]*y[22]*T211
  @inbounds const T229 = y[25]^T27
  @inbounds const T231 = T23+params[5]*y[24]*T229
  @inbounds const T247 = y[27]^T27
  @inbounds const T249 = T23+params[5]*y[26]*T247
  @inbounds const T265 = y[29]^T27
  @inbounds const T267 = T23+params[5]*y[28]*T265
  @inbounds const T283 = y[31]^T27
  @inbounds const T285 = T23+params[5]*y[30]*T283
  @inbounds const T301 = y[33]^T27
  @inbounds const T303 = T23+params[5]*y[32]*T301
  @inbounds const T319 = y[35]^T27
  @inbounds const T321 = T23+params[5]*y[34]*T319
  @inbounds const T337 = y[37]^T27
  @inbounds const T339 = T23+params[5]*y[36]*T337
  @inbounds const T355 = y[39]^T27
  @inbounds const T357 = T23+params[5]*y[38]*T355
  @inbounds const T373 = y[41]^T27
  @inbounds const T375 = T23+params[5]*y[40]*T373
  @inbounds const T391 = y[43]^T27
  @inbounds const T393 = T23+params[5]*y[42]*T391
  @inbounds const T409 = y[45]^T27
  @inbounds const T411 = T23+params[5]*y[44]*T409
  @inbounds const T427 = y[47]^T27
  @inbounds const T429 = T23+params[5]*y[46]*T427
  @inbounds const T445 = y[49]^T27
  @inbounds const T447 = T23+params[5]*y[48]*T445
  @inbounds const T463 = y[51]^T27
  @inbounds const T465 = T23+params[5]*y[50]*T463
  @inbounds const T481 = y[53]^T27
  @inbounds const T483 = T23+params[5]*y[52]*T481
  @inbounds const T499 = y[55]^T27
  @inbounds const T501 = T23+params[5]*y[54]*T499
  @inbounds const T517 = y[57]^T27
  @inbounds const T519 = T23+params[5]*y[56]*T517
  @inbounds const T535 = y[59]^T27
  @inbounds const T537 = T23+params[5]*y[58]*T535
  @inbounds const T553 = y[61]^T27
  @inbounds const T555 = T23+params[5]*y[60]*T553
  @inbounds const T571 = y[63]^T27
  @inbounds const T573 = T23+params[5]*y[62]*T571
  @inbounds const T589 = y[65]^T27
  @inbounds const T591 = T23+params[5]*y[64]*T589
  @inbounds const T607 = y[67]^T27
  @inbounds const T609 = T23+params[5]*y[66]*T607
  @inbounds const T625 = y[69]^T27
  @inbounds const T627 = T23+params[5]*y[68]*T625
  @inbounds const T643 = y[71]^T27
  @inbounds const T645 = T23+params[5]*y[70]*T643
  @inbounds const T661 = y[73]^T27
  @inbounds const T663 = T23+params[5]*y[72]*T661
  @inbounds const T679 = y[75]^T27
  @inbounds const T681 = T23+params[5]*y[74]*T679
  @inbounds const T697 = y[77]^T27
  @inbounds const T699 = T23+params[5]*y[76]*T697
  @inbounds const T715 = y[79]^T27
  @inbounds const T717 = T23+params[5]*y[78]*T715
  @inbounds const T733 = y[81]^T27
  @inbounds const T735 = T23+params[5]*y[80]*T733
  @inbounds const T751 = y[83]^T27
  @inbounds const T753 = T23+params[5]*y[82]*T751
  @inbounds const T769 = y[85]^T27
  @inbounds const T771 = T23+params[5]*y[84]*T769
  @inbounds const T787 = y[87]^T27
  @inbounds const T789 = T23+params[5]*y[86]*T787
  @inbounds const T805 = y[89]^T27
  @inbounds const T807 = T23+params[5]*y[88]*T805
  @inbounds const T823 = y[91]^T27
  @inbounds const T825 = T23+params[5]*y[90]*T823
  @inbounds const T841 = y[93]^T27
  @inbounds const T843 = T23+params[5]*y[92]*T841
  @inbounds const T859 = y[95]^T27
  @inbounds const T861 = T23+params[5]*y[94]*T859
  @inbounds const T877 = y[97]^T27
  @inbounds const T879 = T23+params[5]*y[96]*T877
  @inbounds const T895 = y[99]^T27
  @inbounds const T897 = T23+params[5]*y[98]*T895
  @inbounds const T913 = y[101]^T27
  @inbounds const T915 = T23+params[5]*y[100]*T913
  @inbounds const T1077 = y[3]^params[5]
  @inbounds const T1079 = y[5]^params[5]
  @inbounds const T1082 = y[7]^params[5]
  @inbounds const T1085 = y[9]^params[5]
  @inbounds const T1088 = y[11]^params[5]
  @inbounds const T1091 = y[13]^params[5]
  @inbounds const T1094 = y[15]^params[5]
  @inbounds const T1097 = y[17]^params[5]
  @inbounds const T1100 = y[19]^params[5]
  @inbounds const T1103 = y[21]^params[5]
  @inbounds const T1106 = y[23]^params[5]
  @inbounds const T1109 = y[25]^params[5]
  @inbounds const T1112 = y[27]^params[5]
  @inbounds const T1115 = y[29]^params[5]
  @inbounds const T1118 = y[31]^params[5]
  @inbounds const T1121 = y[33]^params[5]
  @inbounds const T1124 = y[35]^params[5]
  @inbounds const T1127 = y[37]^params[5]
  @inbounds const T1130 = y[39]^params[5]
  @inbounds const T1133 = y[41]^params[5]
  @inbounds const T1136 = y[43]^params[5]
  @inbounds const T1139 = y[45]^params[5]
  @inbounds const T1142 = y[47]^params[5]
  @inbounds const T1145 = y[49]^params[5]
  @inbounds const T1148 = y[51]^params[5]
  @inbounds const T1151 = y[53]^params[5]
  @inbounds const T1154 = y[55]^params[5]
  @inbounds const T1157 = y[57]^params[5]
  @inbounds const T1160 = y[59]^params[5]
  @inbounds const T1163 = y[61]^params[5]
  @inbounds const T1166 = y[63]^params[5]
  @inbounds const T1169 = y[65]^params[5]
  @inbounds const T1172 = y[67]^params[5]
  @inbounds const T1175 = y[69]^params[5]
  @inbounds const T1178 = y[71]^params[5]
  @inbounds const T1181 = y[73]^params[5]
  @inbounds const T1184 = y[75]^params[5]
  @inbounds const T1187 = y[77]^params[5]
  @inbounds const T1190 = y[79]^params[5]
  @inbounds const T1193 = y[81]^params[5]
  @inbounds const T1196 = y[83]^params[5]
  @inbounds const T1199 = y[85]^params[5]
  @inbounds const T1202 = y[87]^params[5]
  @inbounds const T1205 = y[89]^params[5]
  @inbounds const T1208 = y[91]^params[5]
  @inbounds const T1211 = y[93]^params[5]
  @inbounds const T1214 = y[95]^params[5]
  @inbounds const T1217 = y[97]^params[5]
  @inbounds const T1220 = y[99]^params[5]
  @inbounds const T1223 = y[101]^params[5]
  @inbounds const T1227 = get_power_deriv(y[1],(-params[2]),1)
  @inbounds const T1228 = params[1]*T1227
  @inbounds const T1340 = 1-T23
  @inbounds g1[1,1]=T1227-T30*T1228;
  @inbounds g1[1,2]=(-(T19*params[5]*T28));
  @inbounds g1[1,3]=(-(T19*params[5]*y[2]*get_power_deriv(y[3],T27,1)));
  @inbounds g1[2,2]=1/y[2]-params[6]*1/y[2];
  @inbounds g1[3,1]=T1227-T51*T1228;
  @inbounds g1[3,4]=(-(T19*params[5]*T49));
  @inbounds g1[3,5]=(-(T19*params[5]*y[4]*get_power_deriv(y[5],T27,1)));
  @inbounds g1[4,4]=1/y[4]-params[6]*1/y[4];
  @inbounds g1[5,1]=T1227-T69*T1228;
  @inbounds g1[5,6]=(-(T19*params[5]*T67));
  @inbounds g1[5,7]=(-(T19*params[5]*y[6]*get_power_deriv(y[7],T27,1)));
  @inbounds g1[6,6]=1/y[6]-params[6]*1/y[6];
  @inbounds g1[7,1]=T1227-T87*T1228;
  @inbounds g1[7,8]=(-(T19*params[5]*T85));
  @inbounds g1[7,9]=(-(T19*params[5]*y[8]*get_power_deriv(y[9],T27,1)));
  @inbounds g1[8,8]=1/y[8]-params[6]*1/y[8];
  @inbounds g1[9,1]=T1227-T105*T1228;
  @inbounds g1[9,10]=(-(T19*params[5]*T103));
  @inbounds g1[9,11]=(-(T19*params[5]*y[10]*get_power_deriv(y[11],T27,1)));
  @inbounds g1[10,10]=1/y[10]-params[6]*1/y[10];
  @inbounds g1[11,1]=T1227-T123*T1228;
  @inbounds g1[11,12]=(-(T19*params[5]*T121));
  @inbounds g1[11,13]=(-(T19*params[5]*y[12]*get_power_deriv(y[13],T27,1)));
  @inbounds g1[12,12]=1/y[12]-params[6]*1/y[12];
  @inbounds g1[13,1]=T1227-T141*T1228;
  @inbounds g1[13,14]=(-(T19*params[5]*T139));
  @inbounds g1[13,15]=(-(T19*params[5]*y[14]*get_power_deriv(y[15],T27,1)));
  @inbounds g1[14,14]=1/y[14]-params[6]*1/y[14];
  @inbounds g1[15,1]=T1227-T159*T1228;
  @inbounds g1[15,16]=(-(T19*params[5]*T157));
  @inbounds g1[15,17]=(-(T19*params[5]*y[16]*get_power_deriv(y[17],T27,1)));
  @inbounds g1[16,16]=1/y[16]-params[6]*1/y[16];
  @inbounds g1[17,1]=T1227-T177*T1228;
  @inbounds g1[17,18]=(-(T19*params[5]*T175));
  @inbounds g1[17,19]=(-(T19*params[5]*y[18]*get_power_deriv(y[19],T27,1)));
  @inbounds g1[18,18]=1/y[18]-params[6]*1/y[18];
  @inbounds g1[19,1]=T1227-T195*T1228;
  @inbounds g1[19,20]=(-(T19*params[5]*T193));
  @inbounds g1[19,21]=(-(T19*params[5]*y[20]*get_power_deriv(y[21],T27,1)));
  @inbounds g1[20,20]=1/y[20]-params[6]*1/y[20];
  @inbounds g1[21,1]=T1227-T213*T1228;
  @inbounds g1[21,22]=(-(T19*params[5]*T211));
  @inbounds g1[21,23]=(-(T19*params[5]*y[22]*get_power_deriv(y[23],T27,1)));
  @inbounds g1[22,22]=1/y[22]-params[6]*1/y[22];
  @inbounds g1[23,1]=T1227-T231*T1228;
  @inbounds g1[23,24]=(-(T19*params[5]*T229));
  @inbounds g1[23,25]=(-(T19*params[5]*y[24]*get_power_deriv(y[25],T27,1)));
  @inbounds g1[24,24]=1/y[24]-params[6]*1/y[24];
  @inbounds g1[25,1]=T1227-T249*T1228;
  @inbounds g1[25,26]=(-(T19*params[5]*T247));
  @inbounds g1[25,27]=(-(T19*params[5]*y[26]*get_power_deriv(y[27],T27,1)));
  @inbounds g1[26,26]=1/y[26]-params[6]*1/y[26];
  @inbounds g1[27,1]=T1227-T267*T1228;
  @inbounds g1[27,28]=(-(T19*params[5]*T265));
  @inbounds g1[27,29]=(-(T19*params[5]*y[28]*get_power_deriv(y[29],T27,1)));
  @inbounds g1[28,28]=1/y[28]-params[6]*1/y[28];
  @inbounds g1[29,1]=T1227-T285*T1228;
  @inbounds g1[29,30]=(-(T19*params[5]*T283));
  @inbounds g1[29,31]=(-(T19*params[5]*y[30]*get_power_deriv(y[31],T27,1)));
  @inbounds g1[30,30]=1/y[30]-params[6]*1/y[30];
  @inbounds g1[31,1]=T1227-T303*T1228;
  @inbounds g1[31,32]=(-(T19*params[5]*T301));
  @inbounds g1[31,33]=(-(T19*params[5]*y[32]*get_power_deriv(y[33],T27,1)));
  @inbounds g1[32,32]=1/y[32]-params[6]*1/y[32];
  @inbounds g1[33,1]=T1227-T321*T1228;
  @inbounds g1[33,34]=(-(T19*params[5]*T319));
  @inbounds g1[33,35]=(-(T19*params[5]*y[34]*get_power_deriv(y[35],T27,1)));
  @inbounds g1[34,34]=1/y[34]-params[6]*1/y[34];
  @inbounds g1[35,1]=T1227-T339*T1228;
  @inbounds g1[35,36]=(-(T19*params[5]*T337));
  @inbounds g1[35,37]=(-(T19*params[5]*y[36]*get_power_deriv(y[37],T27,1)));
  @inbounds g1[36,36]=1/y[36]-params[6]*1/y[36];
  @inbounds g1[37,1]=T1227-T357*T1228;
  @inbounds g1[37,38]=(-(T19*params[5]*T355));
  @inbounds g1[37,39]=(-(T19*params[5]*y[38]*get_power_deriv(y[39],T27,1)));
  @inbounds g1[38,38]=1/y[38]-params[6]*1/y[38];
  @inbounds g1[39,1]=T1227-T375*T1228;
  @inbounds g1[39,40]=(-(T19*params[5]*T373));
  @inbounds g1[39,41]=(-(T19*params[5]*y[40]*get_power_deriv(y[41],T27,1)));
  @inbounds g1[40,40]=1/y[40]-params[6]*1/y[40];
  @inbounds g1[41,1]=T1227-T393*T1228;
  @inbounds g1[41,42]=(-(T19*params[5]*T391));
  @inbounds g1[41,43]=(-(T19*params[5]*y[42]*get_power_deriv(y[43],T27,1)));
  @inbounds g1[42,42]=1/y[42]-params[6]*1/y[42];
  @inbounds g1[43,1]=T1227-T411*T1228;
  @inbounds g1[43,44]=(-(T19*params[5]*T409));
  @inbounds g1[43,45]=(-(T19*params[5]*y[44]*get_power_deriv(y[45],T27,1)));
  @inbounds g1[44,44]=1/y[44]-params[6]*1/y[44];
  @inbounds g1[45,1]=T1227-T429*T1228;
  @inbounds g1[45,46]=(-(T19*params[5]*T427));
  @inbounds g1[45,47]=(-(T19*params[5]*y[46]*get_power_deriv(y[47],T27,1)));
  @inbounds g1[46,46]=1/y[46]-params[6]*1/y[46];
  @inbounds g1[47,1]=T1227-T447*T1228;
  @inbounds g1[47,48]=(-(T19*params[5]*T445));
  @inbounds g1[47,49]=(-(T19*params[5]*y[48]*get_power_deriv(y[49],T27,1)));
  @inbounds g1[48,48]=1/y[48]-params[6]*1/y[48];
  @inbounds g1[49,1]=T1227-T465*T1228;
  @inbounds g1[49,50]=(-(T19*params[5]*T463));
  @inbounds g1[49,51]=(-(T19*params[5]*y[50]*get_power_deriv(y[51],T27,1)));
  @inbounds g1[50,50]=1/y[50]-params[6]*1/y[50];
  @inbounds g1[51,1]=T1227-T483*T1228;
  @inbounds g1[51,52]=(-(T19*params[5]*T481));
  @inbounds g1[51,53]=(-(T19*params[5]*y[52]*get_power_deriv(y[53],T27,1)));
  @inbounds g1[52,52]=1/y[52]-params[6]*1/y[52];
  @inbounds g1[53,1]=T1227-T501*T1228;
  @inbounds g1[53,54]=(-(T19*params[5]*T499));
  @inbounds g1[53,55]=(-(T19*params[5]*y[54]*get_power_deriv(y[55],T27,1)));
  @inbounds g1[54,54]=1/y[54]-params[6]*1/y[54];
  @inbounds g1[55,1]=T1227-T519*T1228;
  @inbounds g1[55,56]=(-(T19*params[5]*T517));
  @inbounds g1[55,57]=(-(T19*params[5]*y[56]*get_power_deriv(y[57],T27,1)));
  @inbounds g1[56,56]=1/y[56]-params[6]*1/y[56];
  @inbounds g1[57,1]=T1227-T537*T1228;
  @inbounds g1[57,58]=(-(T19*params[5]*T535));
  @inbounds g1[57,59]=(-(T19*params[5]*y[58]*get_power_deriv(y[59],T27,1)));
  @inbounds g1[58,58]=1/y[58]-params[6]*1/y[58];
  @inbounds g1[59,1]=T1227-T555*T1228;
  @inbounds g1[59,60]=(-(T19*params[5]*T553));
  @inbounds g1[59,61]=(-(T19*params[5]*y[60]*get_power_deriv(y[61],T27,1)));
  @inbounds g1[60,60]=1/y[60]-params[6]*1/y[60];
  @inbounds g1[61,1]=T1227-T573*T1228;
  @inbounds g1[61,62]=(-(T19*params[5]*T571));
  @inbounds g1[61,63]=(-(T19*params[5]*y[62]*get_power_deriv(y[63],T27,1)));
  @inbounds g1[62,62]=1/y[62]-params[6]*1/y[62];
  @inbounds g1[63,1]=T1227-T591*T1228;
  @inbounds g1[63,64]=(-(T19*params[5]*T589));
  @inbounds g1[63,65]=(-(T19*params[5]*y[64]*get_power_deriv(y[65],T27,1)));
  @inbounds g1[64,64]=1/y[64]-params[6]*1/y[64];
  @inbounds g1[65,1]=T1227-T609*T1228;
  @inbounds g1[65,66]=(-(T19*params[5]*T607));
  @inbounds g1[65,67]=(-(T19*params[5]*y[66]*get_power_deriv(y[67],T27,1)));
  @inbounds g1[66,66]=1/y[66]-params[6]*1/y[66];
  @inbounds g1[67,1]=T1227-T627*T1228;
  @inbounds g1[67,68]=(-(T19*params[5]*T625));
  @inbounds g1[67,69]=(-(T19*params[5]*y[68]*get_power_deriv(y[69],T27,1)));
  @inbounds g1[68,68]=1/y[68]-params[6]*1/y[68];
  @inbounds g1[69,1]=T1227-T645*T1228;
  @inbounds g1[69,70]=(-(T19*params[5]*T643));
  @inbounds g1[69,71]=(-(T19*params[5]*y[70]*get_power_deriv(y[71],T27,1)));
  @inbounds g1[70,70]=1/y[70]-params[6]*1/y[70];
  @inbounds g1[71,1]=T1227-T663*T1228;
  @inbounds g1[71,72]=(-(T19*params[5]*T661));
  @inbounds g1[71,73]=(-(T19*params[5]*y[72]*get_power_deriv(y[73],T27,1)));
  @inbounds g1[72,72]=1/y[72]-params[6]*1/y[72];
  @inbounds g1[73,1]=T1227-T681*T1228;
  @inbounds g1[73,74]=(-(T19*params[5]*T679));
  @inbounds g1[73,75]=(-(T19*params[5]*y[74]*get_power_deriv(y[75],T27,1)));
  @inbounds g1[74,74]=1/y[74]-params[6]*1/y[74];
  @inbounds g1[75,1]=T1227-T699*T1228;
  @inbounds g1[75,76]=(-(T19*params[5]*T697));
  @inbounds g1[75,77]=(-(T19*params[5]*y[76]*get_power_deriv(y[77],T27,1)));
  @inbounds g1[76,76]=1/y[76]-params[6]*1/y[76];
  @inbounds g1[77,1]=T1227-T717*T1228;
  @inbounds g1[77,78]=(-(T19*params[5]*T715));
  @inbounds g1[77,79]=(-(T19*params[5]*y[78]*get_power_deriv(y[79],T27,1)));
  @inbounds g1[78,78]=1/y[78]-params[6]*1/y[78];
  @inbounds g1[79,1]=T1227-T735*T1228;
  @inbounds g1[79,80]=(-(T19*params[5]*T733));
  @inbounds g1[79,81]=(-(T19*params[5]*y[80]*get_power_deriv(y[81],T27,1)));
  @inbounds g1[80,80]=1/y[80]-params[6]*1/y[80];
  @inbounds g1[81,1]=T1227-T753*T1228;
  @inbounds g1[81,82]=(-(T19*params[5]*T751));
  @inbounds g1[81,83]=(-(T19*params[5]*y[82]*get_power_deriv(y[83],T27,1)));
  @inbounds g1[82,82]=1/y[82]-params[6]*1/y[82];
  @inbounds g1[83,1]=T1227-T771*T1228;
  @inbounds g1[83,84]=(-(T19*params[5]*T769));
  @inbounds g1[83,85]=(-(T19*params[5]*y[84]*get_power_deriv(y[85],T27,1)));
  @inbounds g1[84,84]=1/y[84]-params[6]*1/y[84];
  @inbounds g1[85,1]=T1227-T789*T1228;
  @inbounds g1[85,86]=(-(T19*params[5]*T787));
  @inbounds g1[85,87]=(-(T19*params[5]*y[86]*get_power_deriv(y[87],T27,1)));
  @inbounds g1[86,86]=1/y[86]-params[6]*1/y[86];
  @inbounds g1[87,1]=T1227-T807*T1228;
  @inbounds g1[87,88]=(-(T19*params[5]*T805));
  @inbounds g1[87,89]=(-(T19*params[5]*y[88]*get_power_deriv(y[89],T27,1)));
  @inbounds g1[88,88]=1/y[88]-params[6]*1/y[88];
  @inbounds g1[89,1]=T1227-T825*T1228;
  @inbounds g1[89,90]=(-(T19*params[5]*T823));
  @inbounds g1[89,91]=(-(T19*params[5]*y[90]*get_power_deriv(y[91],T27,1)));
  @inbounds g1[90,90]=1/y[90]-params[6]*1/y[90];
  @inbounds g1[91,1]=T1227-T843*T1228;
  @inbounds g1[91,92]=(-(T19*params[5]*T841));
  @inbounds g1[91,93]=(-(T19*params[5]*y[92]*get_power_deriv(y[93],T27,1)));
  @inbounds g1[92,92]=1/y[92]-params[6]*1/y[92];
  @inbounds g1[93,1]=T1227-T861*T1228;
  @inbounds g1[93,94]=(-(T19*params[5]*T859));
  @inbounds g1[93,95]=(-(T19*params[5]*y[94]*get_power_deriv(y[95],T27,1)));
  @inbounds g1[94,94]=1/y[94]-params[6]*1/y[94];
  @inbounds g1[95,1]=T1227-T879*T1228;
  @inbounds g1[95,96]=(-(T19*params[5]*T877));
  @inbounds g1[95,97]=(-(T19*params[5]*y[96]*get_power_deriv(y[97],T27,1)));
  @inbounds g1[96,96]=1/y[96]-params[6]*1/y[96];
  @inbounds g1[97,1]=T1227-T897*T1228;
  @inbounds g1[97,98]=(-(T19*params[5]*T895));
  @inbounds g1[97,99]=(-(T19*params[5]*y[98]*get_power_deriv(y[99],T27,1)));
  @inbounds g1[98,98]=1/y[98]-params[6]*1/y[98];
  @inbounds g1[99,1]=T1227-T915*T1228;
  @inbounds g1[99,100]=(-(T19*params[5]*T913));
  @inbounds g1[99,101]=(-(T19*params[5]*y[100]*get_power_deriv(y[101],T27,1)));
  @inbounds g1[100,100]=1/y[100]-params[6]*1/y[100];
  @inbounds g1[101,1]=params[9];
  @inbounds g1[101,2]=(-T1077);
  @inbounds g1[101,3]=T1340-y[2]*get_power_deriv(y[3],params[5],1);
  @inbounds g1[101,4]=(-T1079);
  @inbounds g1[101,5]=T1340-y[4]*get_power_deriv(y[5],params[5],1);
  @inbounds g1[101,6]=(-T1082);
  @inbounds g1[101,7]=T1340-y[6]*get_power_deriv(y[7],params[5],1);
  @inbounds g1[101,8]=(-T1085);
  @inbounds g1[101,9]=T1340-y[8]*get_power_deriv(y[9],params[5],1);
  @inbounds g1[101,10]=(-T1088);
  @inbounds g1[101,11]=T1340-y[10]*get_power_deriv(y[11],params[5],1);
  @inbounds g1[101,12]=(-T1091);
  @inbounds g1[101,13]=T1340-y[12]*get_power_deriv(y[13],params[5],1);
  @inbounds g1[101,14]=(-T1094);
  @inbounds g1[101,15]=T1340-y[14]*get_power_deriv(y[15],params[5],1);
  @inbounds g1[101,16]=(-T1097);
  @inbounds g1[101,17]=T1340-y[16]*get_power_deriv(y[17],params[5],1);
  @inbounds g1[101,18]=(-T1100);
  @inbounds g1[101,19]=T1340-y[18]*get_power_deriv(y[19],params[5],1);
  @inbounds g1[101,20]=(-T1103);
  @inbounds g1[101,21]=T1340-y[20]*get_power_deriv(y[21],params[5],1);
  @inbounds g1[101,22]=(-T1106);
  @inbounds g1[101,23]=T1340-y[22]*get_power_deriv(y[23],params[5],1);
  @inbounds g1[101,24]=(-T1109);
  @inbounds g1[101,25]=T1340-y[24]*get_power_deriv(y[25],params[5],1);
  @inbounds g1[101,26]=(-T1112);
  @inbounds g1[101,27]=T1340-y[26]*get_power_deriv(y[27],params[5],1);
  @inbounds g1[101,28]=(-T1115);
  @inbounds g1[101,29]=T1340-y[28]*get_power_deriv(y[29],params[5],1);
  @inbounds g1[101,30]=(-T1118);
  @inbounds g1[101,31]=T1340-y[30]*get_power_deriv(y[31],params[5],1);
  @inbounds g1[101,32]=(-T1121);
  @inbounds g1[101,33]=T1340-y[32]*get_power_deriv(y[33],params[5],1);
  @inbounds g1[101,34]=(-T1124);
  @inbounds g1[101,35]=T1340-y[34]*get_power_deriv(y[35],params[5],1);
  @inbounds g1[101,36]=(-T1127);
  @inbounds g1[101,37]=T1340-y[36]*get_power_deriv(y[37],params[5],1);
  @inbounds g1[101,38]=(-T1130);
  @inbounds g1[101,39]=T1340-y[38]*get_power_deriv(y[39],params[5],1);
  @inbounds g1[101,40]=(-T1133);
  @inbounds g1[101,41]=T1340-y[40]*get_power_deriv(y[41],params[5],1);
  @inbounds g1[101,42]=(-T1136);
  @inbounds g1[101,43]=T1340-y[42]*get_power_deriv(y[43],params[5],1);
  @inbounds g1[101,44]=(-T1139);
  @inbounds g1[101,45]=T1340-y[44]*get_power_deriv(y[45],params[5],1);
  @inbounds g1[101,46]=(-T1142);
  @inbounds g1[101,47]=T1340-y[46]*get_power_deriv(y[47],params[5],1);
  @inbounds g1[101,48]=(-T1145);
  @inbounds g1[101,49]=T1340-y[48]*get_power_deriv(y[49],params[5],1);
  @inbounds g1[101,50]=(-T1148);
  @inbounds g1[101,51]=T1340-y[50]*get_power_deriv(y[51],params[5],1);
  @inbounds g1[101,52]=(-T1151);
  @inbounds g1[101,53]=T1340-y[52]*get_power_deriv(y[53],params[5],1);
  @inbounds g1[101,54]=(-T1154);
  @inbounds g1[101,55]=T1340-y[54]*get_power_deriv(y[55],params[5],1);
  @inbounds g1[101,56]=(-T1157);
  @inbounds g1[101,57]=T1340-y[56]*get_power_deriv(y[57],params[5],1);
  @inbounds g1[101,58]=(-T1160);
  @inbounds g1[101,59]=T1340-y[58]*get_power_deriv(y[59],params[5],1);
  @inbounds g1[101,60]=(-T1163);
  @inbounds g1[101,61]=T1340-y[60]*get_power_deriv(y[61],params[5],1);
  @inbounds g1[101,62]=(-T1166);
  @inbounds g1[101,63]=T1340-y[62]*get_power_deriv(y[63],params[5],1);
  @inbounds g1[101,64]=(-T1169);
  @inbounds g1[101,65]=T1340-y[64]*get_power_deriv(y[65],params[5],1);
  @inbounds g1[101,66]=(-T1172);
  @inbounds g1[101,67]=T1340-y[66]*get_power_deriv(y[67],params[5],1);
  @inbounds g1[101,68]=(-T1175);
  @inbounds g1[101,69]=T1340-y[68]*get_power_deriv(y[69],params[5],1);
  @inbounds g1[101,70]=(-T1178);
  @inbounds g1[101,71]=T1340-y[70]*get_power_deriv(y[71],params[5],1);
  @inbounds g1[101,72]=(-T1181);
  @inbounds g1[101,73]=T1340-y[72]*get_power_deriv(y[73],params[5],1);
  @inbounds g1[101,74]=(-T1184);
  @inbounds g1[101,75]=T1340-y[74]*get_power_deriv(y[75],params[5],1);
  @inbounds g1[101,76]=(-T1187);
  @inbounds g1[101,77]=T1340-y[76]*get_power_deriv(y[77],params[5],1);
  @inbounds g1[101,78]=(-T1190);
  @inbounds g1[101,79]=T1340-y[78]*get_power_deriv(y[79],params[5],1);
  @inbounds g1[101,80]=(-T1193);
  @inbounds g1[101,81]=T1340-y[80]*get_power_deriv(y[81],params[5],1);
  @inbounds g1[101,82]=(-T1196);
  @inbounds g1[101,83]=T1340-y[82]*get_power_deriv(y[83],params[5],1);
  @inbounds g1[101,84]=(-T1199);
  @inbounds g1[101,85]=T1340-y[84]*get_power_deriv(y[85],params[5],1);
  @inbounds g1[101,86]=(-T1202);
  @inbounds g1[101,87]=T1340-y[86]*get_power_deriv(y[87],params[5],1);
  @inbounds g1[101,88]=(-T1205);
  @inbounds g1[101,89]=T1340-y[88]*get_power_deriv(y[89],params[5],1);
  @inbounds g1[101,90]=(-T1208);
  @inbounds g1[101,91]=T1340-y[90]*get_power_deriv(y[91],params[5],1);
  @inbounds g1[101,92]=(-T1211);
  @inbounds g1[101,93]=T1340-y[92]*get_power_deriv(y[93],params[5],1);
  @inbounds g1[101,94]=(-T1214);
  @inbounds g1[101,95]=T1340-y[94]*get_power_deriv(y[95],params[5],1);
  @inbounds g1[101,96]=(-T1217);
  @inbounds g1[101,97]=T1340-y[96]*get_power_deriv(y[97],params[5],1);
  @inbounds g1[101,98]=(-T1220);
  @inbounds g1[101,99]=T1340-y[98]*get_power_deriv(y[99],params[5],1);
  @inbounds g1[101,100]=(-T1223);
  @inbounds g1[101,101]=T1340-y[100]*get_power_deriv(y[101],params[5],1);
  if ~isreal(g1)
    g1 = real(g1)+2*imag(g1);
  end
end

function static!(y::Vector{Float64}, x::Vector{Float64}, params::Vector{Float64},
                 residual::Vector{Float64}, g1::Matrix{Float64}, g2::Matrix{Float64})
#=
## Function Arguments

## Input
 1 y:         Array{Float64, length(model.endo), 1}             Vector of endogenous variables in declaration order
 2 x:         Array{Float64, length(model.exo), 1}              Vector of exogenous variables in declaration order
 3 params:    Array{Float64, length(model.param), 1}            Vector of parameter values in declaration order

## Output
 4 residual:  Array(Float64, model.eq_nbr, 1)                   Vector of residuals of the static model equations
                                                                in order of declaration of the equations.
                                                                Dynare may prepend auxiliary equations, see model.aux_vars
 5 g1:        Array(Float64, model.eq_nbr, length(model.endo))  Jacobian matrix of the static model equations;
                                                                columns: variables in declaration order
                                                                rows: equations in order of declaration
 6 g2:        spzeros(model.eq_nbr, length(model.endo)^2)       Hessian matrix of the static model equations;
                                                                columns: variables in declaration order
                                                                rows: equations in order of declaration
=#
  @assert size(g2) == (101, 10201)
  static!(y, x, params, residual, g1)
end

function static!(y::Vector{Float64}, x::Vector{Float64}, params::Vector{Float64},
                 residual::Vector{Float64}, g1::Matrix{Float64}, g2::Matrix{Float64},
                 g3::Matrix{Float64})
#=
## Function Arguments

## Input
 1 y:         Array{Float64, length(model.endo), 1}             Vector of endogenous variables in declaration order
 2 x:         Array{Float64, length(model.exo), 1}              Vector of exogenous variables in declaration order
 3 params:    Array{Float64, length(model.param), 1}            Vector of parameter values in declaration order

## Output
 4 residual:  Array(Float64, model.eq_nbr, 1)                   Vector of residuals of the static model equations
                                                                in order of declaration of the equations.
                                                                Dynare may prepend auxiliary equations, see model.aux_vars
 5 g1:        Array(Float64, model.eq_nbr, length(model.endo))  Jacobian matrix of the static model equations;
                                                                columns: variables in declaration order
                                                                rows: equations in order of declaration
 6 g2:        spzeros(model.eq_nbr, length(model.endo)^2)       Hessian matrix of the static model equations;
                                                                columns: variables in declaration order
                                                                rows: equations in order of declaration
 7 g3:        spzeros(model.eq_nbr, length(model.endo)^3)       Third derivatives matrix of the static model equations;
                                                                columns: variables in declaration order
                                                                rows: equations in order of declaration
=#
  @assert size(g3) == (101, 1030301)
  static!(y, x, params, residual, g1, g2)
end
end
