module q3a50
#
# NB: this file was automatically generated by Dynare
#     from q3a50.mod
#

using DynareModel
using DynareOptions
using DynareOutput

using Utils
#using SteadyState

using q3a50Static
using q3a50Dynamic
if isfile("q3a50SteadyState.jl")
    using q3a50SteadyState
end
if isfile("q3a50SteadyState2.jl")
    using q3a50SteadyState2
end

export model_, options_, oo_

oo_ = dynare_output()
oo_.dynare_version = "4.5-unstable"

options_ = dynare_options()
options_.dynare_version = "4.5-unstable"

model_ = dynare_model()
model_.fname = "q3a50"
model_.dynare_version = "4.5-unstable"
model_.sigma_e = zeros(Float64, 51, 51)
model_.correlation_matrix = ones(Float64, 51, 51)
model_.orig_eq_nbr = 101
model_.eq_nbr = 101
model_.ramsey_eq_nbr = 0
model_.h = zeros(Float64, 1, 1)
model_.correlation_matrix_me = ones(Float64, 1, 1)
# Endogenous Variables
model_.endo = [
              DynareModel.Endo("c", "c", "c")
              DynareModel.Endo("a1", "a1", "a1")
              DynareModel.Endo("k1", "k1", "k1")
              DynareModel.Endo("a2", "a2", "a2")
              DynareModel.Endo("k2", "k2", "k2")
              DynareModel.Endo("a3", "a3", "a3")
              DynareModel.Endo("k3", "k3", "k3")
              DynareModel.Endo("a4", "a4", "a4")
              DynareModel.Endo("k4", "k4", "k4")
              DynareModel.Endo("a5", "a5", "a5")
              DynareModel.Endo("k5", "k5", "k5")
              DynareModel.Endo("a6", "a6", "a6")
              DynareModel.Endo("k6", "k6", "k6")
              DynareModel.Endo("a7", "a7", "a7")
              DynareModel.Endo("k7", "k7", "k7")
              DynareModel.Endo("a8", "a8", "a8")
              DynareModel.Endo("k8", "k8", "k8")
              DynareModel.Endo("a9", "a9", "a9")
              DynareModel.Endo("k9", "k9", "k9")
              DynareModel.Endo("a10", "a10", "a10")
              DynareModel.Endo("k10", "k10", "k10")
              DynareModel.Endo("a11", "a11", "a11")
              DynareModel.Endo("k11", "k11", "k11")
              DynareModel.Endo("a12", "a12", "a12")
              DynareModel.Endo("k12", "k12", "k12")
              DynareModel.Endo("a13", "a13", "a13")
              DynareModel.Endo("k13", "k13", "k13")
              DynareModel.Endo("a14", "a14", "a14")
              DynareModel.Endo("k14", "k14", "k14")
              DynareModel.Endo("a15", "a15", "a15")
              DynareModel.Endo("k15", "k15", "k15")
              DynareModel.Endo("a16", "a16", "a16")
              DynareModel.Endo("k16", "k16", "k16")
              DynareModel.Endo("a17", "a17", "a17")
              DynareModel.Endo("k17", "k17", "k17")
              DynareModel.Endo("a18", "a18", "a18")
              DynareModel.Endo("k18", "k18", "k18")
              DynareModel.Endo("a19", "a19", "a19")
              DynareModel.Endo("k19", "k19", "k19")
              DynareModel.Endo("a20", "a20", "a20")
              DynareModel.Endo("k20", "k20", "k20")
              DynareModel.Endo("a21", "a21", "a21")
              DynareModel.Endo("k21", "k21", "k21")
              DynareModel.Endo("a22", "a22", "a22")
              DynareModel.Endo("k22", "k22", "k22")
              DynareModel.Endo("a23", "a23", "a23")
              DynareModel.Endo("k23", "k23", "k23")
              DynareModel.Endo("a24", "a24", "a24")
              DynareModel.Endo("k24", "k24", "k24")
              DynareModel.Endo("a25", "a25", "a25")
              DynareModel.Endo("k25", "k25", "k25")
              DynareModel.Endo("a26", "a26", "a26")
              DynareModel.Endo("k26", "k26", "k26")
              DynareModel.Endo("a27", "a27", "a27")
              DynareModel.Endo("k27", "k27", "k27")
              DynareModel.Endo("a28", "a28", "a28")
              DynareModel.Endo("k28", "k28", "k28")
              DynareModel.Endo("a29", "a29", "a29")
              DynareModel.Endo("k29", "k29", "k29")
              DynareModel.Endo("a30", "a30", "a30")
              DynareModel.Endo("k30", "k30", "k30")
              DynareModel.Endo("a31", "a31", "a31")
              DynareModel.Endo("k31", "k31", "k31")
              DynareModel.Endo("a32", "a32", "a32")
              DynareModel.Endo("k32", "k32", "k32")
              DynareModel.Endo("a33", "a33", "a33")
              DynareModel.Endo("k33", "k33", "k33")
              DynareModel.Endo("a34", "a34", "a34")
              DynareModel.Endo("k34", "k34", "k34")
              DynareModel.Endo("a35", "a35", "a35")
              DynareModel.Endo("k35", "k35", "k35")
              DynareModel.Endo("a36", "a36", "a36")
              DynareModel.Endo("k36", "k36", "k36")
              DynareModel.Endo("a37", "a37", "a37")
              DynareModel.Endo("k37", "k37", "k37")
              DynareModel.Endo("a38", "a38", "a38")
              DynareModel.Endo("k38", "k38", "k38")
              DynareModel.Endo("a39", "a39", "a39")
              DynareModel.Endo("k39", "k39", "k39")
              DynareModel.Endo("a40", "a40", "a40")
              DynareModel.Endo("k40", "k40", "k40")
              DynareModel.Endo("a41", "a41", "a41")
              DynareModel.Endo("k41", "k41", "k41")
              DynareModel.Endo("a42", "a42", "a42")
              DynareModel.Endo("k42", "k42", "k42")
              DynareModel.Endo("a43", "a43", "a43")
              DynareModel.Endo("k43", "k43", "k43")
              DynareModel.Endo("a44", "a44", "a44")
              DynareModel.Endo("k44", "k44", "k44")
              DynareModel.Endo("a45", "a45", "a45")
              DynareModel.Endo("k45", "k45", "k45")
              DynareModel.Endo("a46", "a46", "a46")
              DynareModel.Endo("k46", "k46", "k46")
              DynareModel.Endo("a47", "a47", "a47")
              DynareModel.Endo("k47", "k47", "k47")
              DynareModel.Endo("a48", "a48", "a48")
              DynareModel.Endo("k48", "k48", "k48")
              DynareModel.Endo("a49", "a49", "a49")
              DynareModel.Endo("k49", "k49", "k49")
              DynareModel.Endo("a50", "a50", "a50")
              DynareModel.Endo("k50", "k50", "k50")
             ]
# Exogenous Variables
model_.exo = [
             DynareModel.Exo("e", "e", "e")
             DynareModel.Exo("e1", "e1", "e1")
             DynareModel.Exo("e2", "e2", "e2")
             DynareModel.Exo("e3", "e3", "e3")
             DynareModel.Exo("e4", "e4", "e4")
             DynareModel.Exo("e5", "e5", "e5")
             DynareModel.Exo("e6", "e6", "e6")
             DynareModel.Exo("e7", "e7", "e7")
             DynareModel.Exo("e8", "e8", "e8")
             DynareModel.Exo("e9", "e9", "e9")
             DynareModel.Exo("e10", "e10", "e10")
             DynareModel.Exo("e11", "e11", "e11")
             DynareModel.Exo("e12", "e12", "e12")
             DynareModel.Exo("e13", "e13", "e13")
             DynareModel.Exo("e14", "e14", "e14")
             DynareModel.Exo("e15", "e15", "e15")
             DynareModel.Exo("e16", "e16", "e16")
             DynareModel.Exo("e17", "e17", "e17")
             DynareModel.Exo("e18", "e18", "e18")
             DynareModel.Exo("e19", "e19", "e19")
             DynareModel.Exo("e20", "e20", "e20")
             DynareModel.Exo("e21", "e21", "e21")
             DynareModel.Exo("e22", "e22", "e22")
             DynareModel.Exo("e23", "e23", "e23")
             DynareModel.Exo("e24", "e24", "e24")
             DynareModel.Exo("e25", "e25", "e25")
             DynareModel.Exo("e26", "e26", "e26")
             DynareModel.Exo("e27", "e27", "e27")
             DynareModel.Exo("e28", "e28", "e28")
             DynareModel.Exo("e29", "e29", "e29")
             DynareModel.Exo("e30", "e30", "e30")
             DynareModel.Exo("e31", "e31", "e31")
             DynareModel.Exo("e32", "e32", "e32")
             DynareModel.Exo("e33", "e33", "e33")
             DynareModel.Exo("e34", "e34", "e34")
             DynareModel.Exo("e35", "e35", "e35")
             DynareModel.Exo("e36", "e36", "e36")
             DynareModel.Exo("e37", "e37", "e37")
             DynareModel.Exo("e38", "e38", "e38")
             DynareModel.Exo("e39", "e39", "e39")
             DynareModel.Exo("e40", "e40", "e40")
             DynareModel.Exo("e41", "e41", "e41")
             DynareModel.Exo("e42", "e42", "e42")
             DynareModel.Exo("e43", "e43", "e43")
             DynareModel.Exo("e44", "e44", "e44")
             DynareModel.Exo("e45", "e45", "e45")
             DynareModel.Exo("e46", "e46", "e46")
             DynareModel.Exo("e47", "e47", "e47")
             DynareModel.Exo("e48", "e48", "e48")
             DynareModel.Exo("e49", "e49", "e49")
             DynareModel.Exo("e50", "e50", "e50")
            ]
# Parameters
model_.param = [
               DynareModel.Param("beta", "beta", "beta")
               DynareModel.Param("gamma", "gamma", "gamma")
               DynareModel.Param("phi", "phi", "phi")
               DynareModel.Param("delta", "delta", "delta")
               DynareModel.Param("alpha", "alpha", "alpha")
               DynareModel.Param("rho", "rho", "rho")
               DynareModel.Param("zeta", "zeta", "zeta")
               DynareModel.Param("sigma", "sigma", "sigma")
               DynareModel.Param("N", "N", "N")
              ]
model_.orig_endo_nbr = 101
model_.lead_lag_incidence = [
 0 101 202;
 1 102 203;
 2 103 0;
 3 104 204;
 4 105 0;
 5 106 205;
 6 107 0;
 7 108 206;
 8 109 0;
 9 110 207;
 10 111 0;
 11 112 208;
 12 113 0;
 13 114 209;
 14 115 0;
 15 116 210;
 16 117 0;
 17 118 211;
 18 119 0;
 19 120 212;
 20 121 0;
 21 122 213;
 22 123 0;
 23 124 214;
 24 125 0;
 25 126 215;
 26 127 0;
 27 128 216;
 28 129 0;
 29 130 217;
 30 131 0;
 31 132 218;
 32 133 0;
 33 134 219;
 34 135 0;
 35 136 220;
 36 137 0;
 37 138 221;
 38 139 0;
 39 140 222;
 40 141 0;
 41 142 223;
 42 143 0;
 43 144 224;
 44 145 0;
 45 146 225;
 46 147 0;
 47 148 226;
 48 149 0;
 49 150 227;
 50 151 0;
 51 152 228;
 52 153 0;
 53 154 229;
 54 155 0;
 55 156 230;
 56 157 0;
 57 158 231;
 58 159 0;
 59 160 232;
 60 161 0;
 61 162 233;
 62 163 0;
 63 164 234;
 64 165 0;
 65 166 235;
 66 167 0;
 67 168 236;
 68 169 0;
 69 170 237;
 70 171 0;
 71 172 238;
 72 173 0;
 73 174 239;
 74 175 0;
 75 176 240;
 76 177 0;
 77 178 241;
 78 179 0;
 79 180 242;
 80 181 0;
 81 182 243;
 82 183 0;
 83 184 244;
 84 185 0;
 85 186 245;
 86 187 0;
 87 188 246;
 88 189 0;
 89 190 247;
 90 191 0;
 91 192 248;
 92 193 0;
 93 194 249;
 94 195 0;
 95 196 250;
 96 197 0;
 97 198 251;
 98 199 0;
 99 200 252;
 100 201 0;]';
model_.nstatic = 0;
model_.nfwrd   = 1;
model_.npred   = 50;
model_.nboth   = 50;
model_.nsfwrd   = 51;
model_.nspred   = 100;
model_.ndynamic   = 101;
model_.equation_tags = [
                      ]
model_.static_and_dynamic_models_differ = false;
model_.exo_names_orig_ord = collect(1:51);
model_.maximum_lag = 1;
model_.maximum_lead = 1;
model_.maximum_endo_lag = 1;
model_.maximum_endo_lead = 1;
oo_.steady_state = zeros(101)
model_.maximum_exo_lag = 0;
model_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(51)
model_.params = fill(NaN, 9)
model_.nnzderivatives = [601; 1300; -1];
model_.params[ 5 ] = 0.36
model_.params[ 4 ] = 0.1
model_.params[ 3 ] = 2
model_.params[ 2 ] = 1
model_.params[ 1 ] = 0.99
model_.params[ 6 ] = 0.95
model_.params[ 7 ] = 2
model_.params[ 8 ] = 2
model_.params[ 9 ] = 50
model_.static = q3a50Static.static!
model_.dynamic = q3a50Dynamic.dynamic!
if isfile("q3a50SteadyState.jl")
    model_.user_written_analytical_steady_state = true
    model_.steady_state = q3a50SteadyState.steady_state!
end
if isfile("q3a50SteadyState2.jl")
    model_.analytical_steady_state = true
    model_.steady_state = q3a50SteadyState2.steady_state!
end
if isfile("q3a50StaticParamsDerivs.jl")
    using q3a50StaticParamsDerivs
    model_.static_params_derivs = q3a50StaticParamsDerivs.params_derivs
end
if isfile("q3a50DynamicParamsDerivs.jl")
    using q3a50DynamicParamsDerivs
    model_.dynamic_params_derivs = q3a50DynamicParamsDerivs.params_derivs
end
end
